### ISSUE TITLE
Implementation of rqlite-js

### ISSUE THREAD

**Issue by jack-y** [jack-y/seneca-rqlite-store#1]
rqlite-js is the new JavaScript client library available for rqlite.
See: https://www.npmjs.com/package/rqlite-js
This library should replace the actuel http-api and requester modules.

**Comment by justinmorant** [comment]
@jack-y FYI, TravisCI build support is coming to rqlite-js once I get added to the rqlite organization. This comes with unit testing and integration testing as well which is run against the rqlite docker instance.

**Comment by jack-y** [comment]
@justinmorant It sounds good! The rqlite docker instance is already used by this seneca-rqlite-store plugin during tests. The only part that cannot be tested at this time is the 'cluster' feature. As the rqlite-docker documentation says: 

> Instructions for clustering via Docker are forthcoming, but it should not be difficult for people with experience with Docker and networking.

**Comment by jack-y** [comment]
Running all tests with the HTTP-API is +20% faster than with the rqlite-js library.
For now, we retain the current http-api and requester modules.

**Comment by justinmorant** [comment]
@jack-y could you post to this issue how to time your tests as well as a branch I could fork.  I will like to use your setup to tune rqlite-js.

**Comment by jack-y** [comment]
@justinmorant here are my well deserved holidays ;) I will give you everything you want ASAP.

**Comment by jack-y** [comment]
@justinmorant I just pushed a new branch (rqlite-js):
https://github.com/jack-y/seneca-rqlite-store/tree/rqlite-js

Before running the tests, a RQLite node must be started and configured in the `./test/config.js` file.
The command to run the tests: `node ./test/seneca-store-test.js`
The output will show the test duration.

On my computer, testing with the master code (HTTP API) takes about 41".
Testing with the branch code (rqlite-js) takes about 55".
Good luck!
