### ISSUE TITLE
Any handling for HTTP 301 from follower?

### ISSUE THREAD

**Issue by otoolep** [jack-y/seneca-rqlite-store#2]
@jack-y -- does this software do anything special if it gets HTTP 301 back from a node? I.e. dealing with the following?

https://github.com/rqlite/rqlite/blob/master/doc/DATA_API.md#sending-requests-to-followers

**Comment by jack-y** [comment]
@otoolep Yes. As you recommand, in case of a HTTP 301 reply, the `requester` redirects to the leader's URL  (`location` header).
You can see it in action here:
https://github.com/jack-y/seneca-rqlite-store/blob/master/requester.js#L152

Another foreseen behaviour: the node connection timeout.
In case of timeout, and if the Discovery Service URL is set in the configuration file, the `requester` retrieves the URL of the other nodes. Then it tries to connect to.
You can see it in action here:
https://github.com/jack-y/seneca-rqlite-store/blob/master/requester.js#L96

Hope it helps!

**Comment by otoolep** [comment]
OK, I am considering changing the rqlite software to return the full URL, as I think it was mistaken to just send the host and path, without the query params. However it looks like your client will work fine if I make the change.

**Comment by jack-y** [comment]
@otoolep Fine! Perfect for queries (HTTP GET), but what about the parameters of operations like inserts ( HTTP POST)?
Anyway, be assured that I will adapt this client for each of your changes. Please, just tell me.
